version: '3.8'

services:
  lite3_sdk_sim:
    build: .
    image: lite3_sdk_deploy
    container_name: lite3_sdk_sim
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=1
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    stdin_open: true
    tty: true
